export const DEFAULT_CONFIG_FILE = 'api.swagger-types.ts';
export const INTERNAL_DIR = '.better-swagger-types';
export const CACHE_DIR = '.better-swagger-types/cache';
export const MANIFEST_FILE = '.better-swagger-types/manifest.json';
export const NODE_MODULES_MARKER_DIR = 'node_modules/.better-swagger-types';
export const GENERATED_BANNER = `// This file is auto-generated by better-swagger-types. DO NOT EDIT.\n// Run: npx better-swagger-types generate\n\n`;
export const HTTP_METHOD_ORDER = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head', 'trace'] as const;
